project:
  type: website
website:
  title: "R for Statistical Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        file: about.qmd
    right: 
      - text: "Presentation"
        file: Workshop.qmd
      - text: "Materials & Videos"
        file: videos.qmd
      - text: R Workshop
        menu:
          - data_clean.qmd
          - correlation.qmd
          - ttest.qmd
          - regression.qmd
          - ANOVA.qmd
          - factor_analysis.qmd
          - moderation_mediation.qmd
          - nonparametric.qmd
          - SEM.qmd
format:
  html:
    theme: 
      light: [custom.scss]
      dark: [custom.scss,light_custom.scss]