---
title: "Material & Videos"
author: "Brier Gallihugh, M.S."
format: html
preview-links: true
---
## R Basics

The link to the **video** can be found [here](https://drive.google.com/file/d/1hQyyQzsf5CjukioO9yyBNdoxxqZUCeYk/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/16ZHwqt5t79qnkJ7EoJ_ltJ9z8FZAgmHK/view?usp=share_link)

## Data Manipulation

The link to the **video** can be found [here](https://drive.google.com/file/d/1BcDYFAqAFSMDj1s3Lr_R9Vs1XVZOUBq7/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/16ZHwqt5t79qnkJ7EoJ_ltJ9z8FZAgmHK/view?usp=share_link)

## Data Visualization

The link to the **video** can be found [here](https://drive.google.com/file/d/1sn-BKqy1r5HyLuiy_mElJ88_cXrCyFF8/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/16ZHwqt5t79qnkJ7EoJ_ltJ9z8FZAgmHK/view?usp=share_link)

## Correlation

The link to the **video** can be found [here](https://drive.google.com/file/d/1MSCdiG0SH64lL0PyClKqrL-xgnxN0fuK/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1asYLjFdMSXTR1YH_sFc6fuz18cto8nqF/view?usp=share_link)

## T-Tests

The link to the **video** can be found [here](https://drive.google.com/file/d/1tsQogteEQUyBB0ZM9hQTcaUHtPMv8aq7/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1Vo8UkhTv-f5BjlfY9QXaYfgaIGs5h4A8/view?usp=share_link)

## Regression

The link to the **video** can be found [here](https://drive.google.com/file/d/1rfHlAMCd4A4iKp_YF7zoMXPWQxpk-7yb/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1RDFt2DkcJ-OP4-P5r6Utjs41yToZCbsC/view?usp=share_link)

## Logistic Regression

The link to the **video** can be found [here](https://drive.google.com/file/d/1JClJLGbRF-zc1fqlEAFHSXqZtMzOn3cp/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1RDFt2DkcJ-OP4-P5r6Utjs41yToZCbsC/view?usp=share_link)

## ANOVA

The link to the **video** can be found [here](https://drive.google.com/file/d/15UrC_I0RGyXDbD5GQs95d3G8Baa-QkTm/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1N-pOZ5HGGiQtf1ZpUVyr1G92_dEOWwRY/view?usp=share_link)

## Factorial ANOVA

The link to the **video** can be found [here](https://drive.google.com/file/d/1PyIwomVXoN0kFBVgssJE_j7mRGwzixAn/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1N-pOZ5HGGiQtf1ZpUVyr1G92_dEOWwRY/view?usp=share_link)

## Independent Sample T-Test (Non-Parametric)

The link to the **video** can be found [here](https://drive.google.com/file/d/1hVjzEMcsq6EH9Kb2tV-pKsRdA7ZFAK5b/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1oYku7KAaGUp8oj_lR-GV5woCSXV_IXAM/view?usp=share_link)

## Dependent Sample T-Test (Non-Parametric)

The link to the **video** can be found [here](https://drive.google.com/file/d/1hpMw7rfr4hUp9UOWoXMGWy-84ZNu8We4/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1oYku7KAaGUp8oj_lR-GV5woCSXV_IXAM/view?usp=share_link)

## ANOVA (Non-Parametric)

The link to the **video** can be found [here](https://drive.google.com/file/d/15bcwCsOTSRuel3ga4S-xdHPcq5gO6ERC/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1oYku7KAaGUp8oj_lR-GV5woCSXV_IXAM/view?usp=share_link)

## Repeated Measures ANOVA (Non-Parametric)

The link to the **video** can be found [here](https://drive.google.com/file/d/1njk60JvmP3_Gd61-Oul2UMkhyAbc6uXh/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1oYku7KAaGUp8oj_lR-GV5woCSXV_IXAM/view?usp=share_link)

## Mediation

The link to the **video** can be found [here](https://drive.google.com/file/d/198SW2REq7CQAHhUYJl6cK0aqZyWpwLwV/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1wZjr88CoQR6RX9--LibZZRlZkG5Uk_CP/view?usp=share_link)

## Moderation

The link to the **video** can be found [here](https://drive.google.com/file/d/1VgVlRn5GNZxSVHE9GXaT470pjHh9pj6Q/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1wZjr88CoQR6RX9--LibZZRlZkG5Uk_CP/view?usp=share_link)

## Mediation and Moderation (PROCESS)

The link to the **video** can be found [here](https://drive.google.com/file/d/1Y04sw0vGL_EcRNGMZ88uY4du-7IdbPCG/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1wZjr88CoQR6RX9--LibZZRlZkG5Uk_CP/view?usp=share_link)

## Factor Analysis

The link to the **video** can be found [here](https://drive.google.com/file/d/19RKlYxJ6Hc-v34OO-OcDiRZqUz61bAJy/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1smZ2SSqkMU5agif1tzhmQe6lKC0w8O9j/view?usp=share_link)

## Confirmatory Factor Analysis

The link to the **video** can be found [here](https://drive.google.com/file/d/1Ljm_We3Q03YTZ4odwEXgSFj0mcDRoc-3/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1Tf-Cj2qdQ4wmpc12F7b8cCmOxj6Npt_k/view?usp=share_link)

## Structural Equation Modeling

The link to the **video** can be found [here](https://drive.google.com/file/d/1EZriRMHGJbFxID39eCjm81IboMGT8mwW/view?usp=share_link)

The **materials** can be found [here](https://drive.google.com/file/d/1Tf-Cj2qdQ4wmpc12F7b8cCmOxj6Npt_k/view?usp=share_link)



